#!/usr/bin/env sh
git fetch
remoteBranch=$(git symbolic-ref --short -q HEAD)

if [ -n "$1" ]
then
  remoteBranch=$1
fi
echo "Showing logs between $remoteBranch origin/$remoteBranch"
git log $remoteBranch..origin/$remoteBranch --oneline
